version: 0.2
phases:
  install:
    commands: 
      - curl -sL https://deb.nodesource.com/setup_11.x | bash -
      - apt-get install -y nodejs
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage dev | tee deploy.out