service: sentimentbot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  timeout: 60
  environment:
    BOT_TOKEN: ${ssm:bot_token}
    SENTIMENTS_TRACKER_TABLE: sentiments_tracker
    FEATUREFLAG_TABLE: features
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SENTIMENTS_TRACKER_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.FEATUREFLAG_TABLE}"
    - Effect: Allow
      Action:
        - comprehend:DetectSentiment
      Resource: "*"
functions:
  event_receive:
    handler: sentiments/event.receive
    memorySize: 128
    events:
      - http:
          path: event/receive
          method: post
          cors: true
# serverless.yml
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
resources:
  Resources:
    SentimentsTrackerDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: timestamp
            AttributeType: S
        KeySchema:
          -
            AttributeName: timestamp
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.SENTIMENTS_TRACKER_TABLE}
    FeatureFlagDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: feature
            AttributeType: S
        KeySchema:
          -
            AttributeName: feature
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.FEATUREFLAG_TABLE}