service: infobot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

functions:
  event_receive:
    handler: infobot/event.receive
    memorySize: 128
    events:
      - http:
          path: event/receive
          method: post
          cors: true